[build-system]
requires = ["setuptools>=84", "ziglang==0.16.0"]
build-backend = "setuptools.build_meta"

[project]
name = "zig-micrograd"
version = "0.2.0"
requires-python = ">=3.14,<3.15"

dependencies = [
    "setuptools >= 84",
    "ziglang==0.16.0",
    "build==1.6.1",
    "numpy>=2.5.3,<3.0.0",
    "torchvision",
    "torch>=2.14,<3.0.0",
    "matplotlib",
    "pytest>=9.1.1",
    "ipython",
    "ruff",
]

[tool.setuptools]
packages = ["zig_micrograd"]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
